<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'DNSAnswer' => $vendorDir . '/phpclasses/phpresolver/DNS.php',
    'DNSMessageParser' => $vendorDir . '/phpclasses/phpresolver/DNS.php',
    'DNSName' => $vendorDir . '/phpclasses/phpresolver/DNS.php',
    'DNSQuery' => $vendorDir . '/phpclasses/phpresolver/DNS.php',
    'DNSRecord' => $vendorDir . '/phpclasses/phpresolver/DNS.php',
    'DNSResolver' => $vendorDir . '/phpclasses/phpresolver/DNS.php',
    'basic_sasl_client_class' => $vendorDir . '/phpclasses/sasl/basic_sasl_client.php',
    'cram_md5_sasl_client_class' => $vendorDir . '/phpclasses/sasl/cram_md5_sasl_client.php',
    'digest_sasl_client_class' => $vendorDir . '/phpclasses/sasl/digest_sasl_client.php',
    'login_sasl_client_class' => $vendorDir . '/phpclasses/sasl/login_sasl_client.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpclasses/sasl/ntlm_sasl_client.php',
    'plain_sasl_client_class' => $vendorDir . '/phpclasses/sasl/plain_sasl_client.php',
    'sasl_client_class' => $vendorDir . '/phpclasses/sasl/sasl.php',
    'sasl_interact_class' => $vendorDir . '/phpclasses/sasl/sasl.php',
    'smtp_class' => $vendorDir . '/phpclasses/smtpclass/smtp.php',
    'email_message_class' => $vendorDir . '/phpclasses/smtpclass/email_message.php',
    'smtp_message_class' => $vendorDir . '/phpclasses/smtpclass/smtp_message.php',
    'smtp_mail_class' => $vendorDir . '/phpclasses/smtpclass/smtp_mail.php',
    'ccproto' => $vendorDir . '/decaptcher/ccproto_client.php',
    'Freenom_Client' => $vendorDir . '/Freenom/Client.php',
	'Freenom_Contact' => $vendorDir . '/Freenom/Contact.php',

	'Freenom_Domain' => $vendorDir . '/Freenom/Domain.php',
	'Freenom_Exception' => $vendorDir . '/Exception.php',

	'Freenom_Service' => $vendorDir . '/Freenom/Service.php',
	'Freenom_IO_Curl' => $vendorDir . '/Freenom/IO/Curl.php',
   'simple_html_dom_class' => $vendorDir . '/simple_html_dom.php',//mongoapi.class.php
   'MongoAPI' => $vendorDir . '/mongo-api-php/mongoapi.class.php',
   'Api' => $vendorDir . '/php-ovh/vendor/autoload.php',


);
